spring:
    datasource:
        url: jdbc:h2:tcp://localhost/~/Calcul;
        username: sa
        password: 1111
        driver-class-name: org.h2.Driver

    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format-sql: true
                default-batch-fetch-size: 100
        show-sql: true

logging:
    level:
        org-hibernate-SQL: DEBUG
        org-hibernate-type: TRACE
        org-springframework-jdbc-core-JdbcTemplate: DEBUG
        org-springframework-jdbc-core-StatementCreatorUtils: TRACE